### ISSUE TITLE
Naming consistency: ShellyPlusPmMiniExporter incorrectly uses Camel case for metric prefix

### ISSUE THREAD

**Issue by jfallot** [lukassoo/ShellyExporters#12]
In https://github.com/lukassoo/ShellyExporters/blob/main/ShellyPlusPmMiniExporter/Program.cs ShellyPlusPmMini_ metric prefix should be renamed shellypluspmmini_ for consistency with other exporters

**Comment by lukassoo** [comment]
Since you are probably the only user of this exporter at this moment, we can change the metric names. 👍
