### ISSUE TITLE
Bind mount failed: '/etc/shelly3EmExporter' does not exists.

### ISSUE THREAD

**Issue by phila63** [lukassoo/ShellyExporters#3]
When executing docker run, container stops and returns 
docker: Error response from daemon: Bind mount failed: '/etc/shelly3EmExporter' does not exists.

I believe if there was no config it would be written after the initial run and stop.

Maybe I've missed something in the installation/configuration?

**Comment by lukassoo** [comment]
The directory '/etc/shelly3EmExporter' has to exist for the binding (the "-v /etc/shelly3EmExporter:/Config" part of the command)

You can simply create it with the command:
`mkdir /etc/shelly3EmExporter`
Then the binding will go through.

The "etc" directory is used for configuration files so thats why I chose it as a default directory.
You can always change that part of the command and choose your own directory.

Let me know if it works 🙂

**Comment by phila63** [comment]
Thank you, that worked.
Homer Simpson "DOH" moment for me.
