### ISSUE TITLE
Docker Container shelly-3em-exporter:armv8 not working 

### ISSUE THREAD

**Issue by tarantila** [lukassoo/ShellyExporters#6]
While trying to use this repo with the following run-command:

`docker run --name Shelly3EmExporter -d -p 9946:9946 -v /data/exporter/shellyexporter/Config:/Config lukassoo/shelly-3em-exporter:armv8`

the container crashes without generating a YAML configfile. The docker logs say that there is a missing "Shelly3EMExporter.dll":

```
> docker logs c0aa1f07384f
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'Shelly3EMExporter.dll' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
```

**Comment by lukassoo** [comment]
Hi!
There was indeed a typo in the docker file.
I fixed it and tried to run a new build that started the application.
I have not yet tested on an actual ARM device but I have pushed the new image to Docker Hub.

Could you remove the old image, try the new one, and tell me if it works?
I'll be able to test it on a Raspberry later.
Once everything works I"ll also update the remaining images in case they had this issue too.

**Comment by tarantila** [comment]
Hey! 
I tried the new container on my Pi and it works now :) 
So the issue is fixed. Thanks.
