### ISSUE TITLE
Problem with ShellyPlusPlugExporter image

### ISSUE THREAD

**Issue by dtolgyg** [lukassoo/ShellyExporters#9]
I have been using the exporter for Shelly Plus Plugs since some months. After pulling latest image sha256:3cc8698c84ee350b55691de79391fc37f7024bc068801463986cc5277607e003, on x86_64, container exits with following error:

```
# docker run --name ShellyPlusPlugExporter -d -p 10009:10009 -v ./shelly:/Config lukassoo/shelly-plus-plug-exporter:latest
b74878846b8b3973afe293026b7ce6d806e7cca3ad597149334a11becb0e9f86
# docker logs ShellyPlusPlugExporter
exec /usr/bin/dotnet: exec format error
```

Please let me know if any further details are needed.

**Comment by lukassoo** [comment]
It seems an ARM executable was pushed to the "latest" docker tag somehow.
I have re-built the image, pushed it, and pulled it on another machine and it appears to be working now.

I am unsure as to how this happened 🤔
The build process is automated and the issue should be present in all exporters if it were there.
I am still manually pushing the built images but they already have tags set so swapping on accident should not be possible.
I hope there isn't a rare race condition hiding somewhere.

@dtolgyg Let me know it the image now works as intended once more.

**Comment by dtolgyg** [comment]
Hi,
I have tested the new image, and indeed it works again.
Thank you, for addressing this issue so quickly.
